insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('009767302-1', 'sem mauris laoreet ut', 'XS', 'Violet');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('971742258-3', 'rutrum neque aenean auctor', 'S', 'Teal');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('221694103-4', 'tincidunt in leo maecenas', 'XL', 'Orange');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('438720458-3', 'eleifend quam a odio', 'L', 'Aquamarine');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('017729131-1', 'arcu', 'XL', 'Fuscia');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('710858278-3', 'orci luctus et', 'XS', 'Fuscia');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('427008347-6', 'potenti in eleifend', 'L', 'Crimson');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('083845908-0', 'vestibulum sagittis', 'S', 'Red');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('715841024-2', 'aenean fermentum donec ut', 'L', 'Mauv');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('765212662-2', 'semper interdum mauris ullamcorper', 'M', 'Orange');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('462240174-6', 'posuere metus vitae ipsum', '3XL', 'Turquoise');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('900365072-1', 'tortor eu pede', 'S', 'Khaki');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('858700603-7', 'suscipit ligula', 'XL', 'Khaki');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('201498593-6', 'mi in', 'M', 'Aquamarine');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('822671101-0', 'in sagittis dui vel', 'S', 'Turquoise');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('692341024-X', 'dictumst etiam', '2XL', 'Teal');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('261766863-0', 'sit amet', 'L', 'Green');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('399976034-6', 'eu', 'XL', 'Purple');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('365718530-5', 'condimentum neque sapien placerat', '2XL', 'Green');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('627782555-0', 'vehicula', '2XL', 'Turquoise');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('967369690-X', 'porta', '2XL', 'Green');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('087733403-X', 'convallis morbi odio odio', '2XL', 'Red');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('594834463-0', 'etiam faucibus cursus urna', 'L', 'Pink');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('156519645-7', 'luctus et ultrices', 'XL', 'Violet');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('634792576-1', 'sit amet', 'M', 'Orange');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('367702439-0', 'egestas metus aenean', 'L', 'Indigo');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('073294954-8', 'vulputate luctus cum', 'XL', 'Khaki');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('041893440-1', 'eget tempus', 'XL', 'Blue');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('828131934-8', 'augue', '3XL', 'Fuscia');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('531485840-1', 'at lorem integer tincidunt', 'XS', 'Red');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('733229342-0', 'sed nisl nunc', '2XL', 'Goldenrod');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('125145719-3', 'lorem integer tincidunt', 'L', 'Yellow');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('249884316-7', 'aliquet at feugiat', '2XL', 'Fuscia');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('364433202-9', 'mauris sit amet', '2XL', 'Aquamarine');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('849366005-1', 'vestibulum ante ipsum', '3XL', 'Purple');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('994277203-0', 'turpis enim blandit mi', 'XL', 'Indigo');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('110474307-8', 'praesent lectus', 'L', 'Maroon');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('282261682-5', 'duis', 'M', 'Indigo');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('166540309-8', 'nullam molestie nibh in', 'L', 'Indigo');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('095055398-0', 'quis tortor', 'S', 'Goldenrod');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('538495643-7', 'justo sit amet', 'S', 'Orange');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('069575157-3', 'metus', 'M', 'Yellow');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('512140791-2', 'dui proin leo', 'L', 'Indigo');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('882602081-7', 'nulla', 'XL', 'Indigo');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('270956768-7', 'id turpis integer', 'S', 'Khaki');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('838771471-2', 'eget semper', 'XS', 'Violet');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('346323087-9', 'turpis elementum ligula', 'M', 'Turquoise');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('630316641-5', 'nunc', '2XL', 'Indigo');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('826024834-4', 'sem duis aliquam', 'XL', 'Turquoise');
insert into ITEM ("ItemSKU", "ItemName", "Size", "Color") values ('378730351-0', 'ipsum aliquam non', '3XL', 'Purple');
